FROM nginx
RUN useradd -ms /bin/bash appuser
WORKDIR /home/

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./server.c .
COPY ./run.sh .

RUN chmod +x run.sh \
    && apt update \
    && apt install -y gcc spawn-fcgi libfcgi-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && chown -R appuser:appuser /home
USER appuser

ENTRYPOINT ["./run.sh"]