FROM nginx

WORKDIR /home/

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./server.c .
COPY ./run.sh .

RUN chmod +x run.sh \
    && apt update \
    && apt install -y gcc spawn-fcgi libfcgi-dev \
    && gcc server.c -lfcgi -o server

ENTRYPOINT ["./run.sh"]